<script setup lang="ts">
/**
 * EvolutionReviewPanel — BUG-5 + E21 + E22 fix.
 *
 * Replaces the old ReviewQueuePanel (which read /admin/review-queue —
 * a dead legacy `review_queue` table with 0 rows).
 *
 * Now reads `/evolution/review-queue?limit=200` (E21 fix: was hard-coded
 * 50 which capped the queue at 50 rows even when 143+ items exist).
 *
 * Adds a "批量拒绝" button (E21 fix) that POSTs to
 * `/evolution/review-queue/batch-action` to bulk-reject items that were
 * generated by an empty-snapshot diff (false positive "removed" events).
 *
 * E22 fix: per-row 批准/拒绝 buttons are now wired to
 * `/evolution/review-queue/{id}/action` (the previously hard-coded
 * `disabled` left users no way to handle individual items).
 */
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import request from '@/api/request'
import { useEvolutionStore } from '@/stores/evolution'

const evo = useEvolutionStore()
const batchRejecting = ref(false)
const actioningIds = ref<Set<string>>(new Set())

onMounted(() => {
  evo.fetchReviewQueue('pending').catch(() => null)
})

async function handleBatchReject() {
  try {
    await ElMessageBox.confirm(
      `确认批量拒绝当前所有「低信任度」待审演化变更？\n\n此操作将拒绝队列中全部 EvolutionChangelog WHERE status='pending' AND trust_score<0.5。\n通常用于清理 diff_engine 在 snapshot 重建时产生的误报「removed」事件。`,
      '批量拒绝确认',
      {
        confirmButtonText: '确认全部拒绝',
        cancelButtonText: '取消',
        type: 'warning',
      },
    )
  } catch {
    return
  }
  batchRejecting.value = true
  const progressMsg = ElMessage({
    message: '正在批量拒绝...',
    type: 'info',
    duration: 0,
  })
  try {
    // E22 fix: use the shared request lib (auto-handles auth + 401).
    // response interceptor returns response.data, not the raw axios response.
    const data = await request.post('/evolution/review-queue/batch-action', { action: 'reject' }) as { updated: number; matched: number }
    progressMsg.close()
    ElMessage.success(`已批量拒绝 ${data.updated ?? 0} 个变更 (匹配 ${data.matched ?? 0} 条)`)
    await evo.fetchReviewQueue('pending')
  } catch (e) {
    progressMsg.close()
    ElMessage.error('批量拒绝失败: ' + (e instanceof Error ? e.message : '未知错误'))
  } finally {
    batchRejecting.value = false
  }
}

async function handleSingleAction(row: { id: string; skill_name: string; position_name: string }, action: 'approve' | 'reject') {
  if (!row.id) {
    ElMessage.error('该行缺少 changelog id,无法执行单项操作')
    return
  }
  // Mark this row as "acting" so the buttons show loading per-row.
  actioningIds.value.add(row.id)
  try {
    await request.post(
      `/evolution/review-queue/${row.id}/action`,
      { action },
    )
    ElMessage.success(
      `已${action === 'approve' ? '批准' : '拒绝'}: ${row.skill_name ?? '-'} / ${row.position_name ?? '-'}`,
    )
    await evo.fetchReviewQueue('pending')
  } catch (e) {
    ElMessage.error(
      '操作失败: ' + (e instanceof Error ? e.message : '未知错误'),
    )
  } finally {
    actioningIds.value.delete(row.id)
  }
}

function formatDate(iso: string): string {
  if (!iso) return '—'
  try {
    return new Date(iso).toLocaleString()
  } catch {
    return iso
  }
}

function changeTypeLabel(t: string): string {
  const map: Record<string, string> = {
    added_required: '新增必备',
    added_preferred: '新增优先',
    promoted: '提升',
    demoted: '降级',
    retained: '保留',
    removed: '移除',
  }
  return map[t] ?? t
}
</script>

<template>
  <div class="evolution-review-panel">
    <!-- E21 fix: tool bar with bulk-reject action to clean up false-positive
         "removed" events caused by diff_engine empty-snapshot handling. -->
    <div v-if="evo.reviewQueue.length > 0" class="review-toolbar">
      <span class="toolbar-text">
        共 <strong>{{ evo.reviewQueue.length }}</strong> 个低信任度变更待审
      </span>
      <el-button
        type="danger"
        size="small"
        :loading="batchRejecting"
        @click="handleBatchReject"
      >
        批量拒绝（清理误报）
      </el-button>
    </div>

    <el-alert
      v-if="evo.reviewQueue.length === 0 && !evo.reviewQueueLoading"
      type="info"
      :closable="false"
      show-icon
      class="empty-alert"
    >
      <template #title>
        当前没有待审核的低信任度演化变更
      </template>
      <p>演化 orchestrator 每周自动运行；只有 trust_score &lt; 0.5 的变更会进入此队列等待人工裁决。</p>
    </el-alert>

    <el-table
      v-else
      v-loading="evo.reviewQueueLoading"
      :data="evo.reviewQueue"
      stripe
      border
      style="width: 100%"
    >
      <el-table-column
        prop="skill_name"
        label="技能"
        min-width="160"
      >
        <template #default="{ row }">
          {{ row.skill_name || '—' }}
        </template>
      </el-table-column>
      <el-table-column
        prop="position_name"
        label="岗位"
        min-width="160"
      >
        <template #default="{ row }">
          {{ row.position_name || '—' }}
        </template>
      </el-table-column>
      <el-table-column
        prop="change_type"
        label="变更类型"
        min-width="120"
      >
        <template #default="{ row }">
          <el-tag size="small">
            {{ changeTypeLabel(row.change_type) }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column
        prop="trust_score"
        label="变更置信度"
        width="120"
        sortable
      >
        <template #default="{ row }">
          <el-progress
            :percentage="Math.round(row.trust_score * 100)"
            :stroke-width="10"
            :status="row.trust_score < 0.3 ? 'exception' : 'warning'"
          />
        </template>
      </el-table-column>
      <el-table-column
        prop="created_at"
        label="检测时间"
        min-width="180"
      >
        <template #default="{ row }">
          {{ formatDate(row.created_at) }}
        </template>
      </el-table-column>
      <el-table-column
        label="操作"
        width="180"
        fixed="right"
      >
        <template #default="{ row }">
          <el-button
            size="small"
            type="success"
            plain
            :loading="actioningIds.has(row.id)"
            :disabled="!row.id"
            @click="handleSingleAction(row, 'approve')"
          >
            批准
          </el-button>
          <el-button
            size="small"
            type="danger"
            plain
            :loading="actioningIds.has(row.id)"
            :disabled="!row.id"
            @click="handleSingleAction(row, 'reject')"
          >
            拒绝
          </el-button>
        </template>
      </el-table-column>
    </el-table>

    <p class="data-source">
      数据源: <code>GET /evolution/review-queue?status=pending</code>
      （EvolutionChangelog WHERE status='pending' AND trust_score &lt; 0.5）
    </p>
  </div>
</template>

<style scoped>
.evolution-review-panel {
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.empty-alert {
  margin-bottom: 8px;
}
.review-toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 8px 12px;
  background: var(--el-color-warning-light-9, #fdf6ec);
  border: 1px solid var(--el-color-warning-light-5, #faecd8);
  border-radius: 6px;
  margin-bottom: 4px;
}
.toolbar-text {
  font-size: 13px;
  color: var(--foreground);
}
.toolbar-text strong {
  color: var(--el-color-warning-dark-2, #b88230);
  font-weight: 700;
  margin: 0 2px;
}
.data-source {
  font-size: 12px;
  color: var(--muted-foreground);
  margin: 8px 0 0;
}
.data-source code {
  background: var(--muted);
  padding: 1px 6px;
  border-radius: 4px;
}
</style>