"""CI guard (CONCERN 4.2): verify `frontend/src/api/schema.ts` is the
generated artifact, not a hand-edited file.

openapi-typescript writes a fixed header line:
    * This file was auto-generated by openapi-typescript.
    * Do not make direct changes to the file.

This guard fails if the header is missing or the file looks hand-edited
(otherwise a contributor's silent edit to schema.ts ships unflagged).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
SCHEMA_TS = REPO / "frontend" / "src" / "api" / "schema.ts"

EXPECTED_LINES = [
    "This file was auto-generated by openapi-typescript.",
    "Do not make direct changes to the file.",
]


def main() -> int:
    if not SCHEMA_TS.exists():
        print(f"OK: {SCHEMA_TS} does not exist yet (skip).")
        return 0

    head = SCHEMA_TS.read_text(encoding="utf-8")[:2048]
    missing = [line for line in EXPECTED_LINES if line not in head]
    if missing:
        print("ERROR: frontend/src/api/schema.ts is missing the generated-header marker.")
        print("Expected lines (in the first 2 KB):")
        for line in missing:
            print(f"  - {line!r}")
        print()
        print(
            "Either the file was hand-edited (revert and regenerate via "
            "`npm run gen:api`) or openapi-typescript changed its header format "
            "(update EXPECTED_LINES)."
        )
        return 1

    # Heuristic: count import-from-@apidevtools lines (present in real
    # openapi-typescript output). Hand-edits usually remove them.
    n_imports = len(re.findall(r"from ['\"]@apidevtools", head))
    if n_imports == 0:
        print("WARN: schema.ts does not reference @apidevtools — may be hand-written.")
        return 0  # warn-only

    print(f"OK: schema.ts has generated header ({n_imports} @apidevtools imports).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
